# Generated by Django 3.0.8 on 2020-07-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='list_category',
            new_name='todolist_category',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='list_name',
            new_name='todolist_name',
        ),
    ]
